source 'https://rubygems.org' do
  gem 'cocoapods', :git => 'https://github.com/CocoaPods/CocoaPods', :ref => 'ecb9a4d0bececbd76db72e4ca95c265bfbbc0bf4'
  gem 'cocoapods-binary', :git => 'https://github.com/mobilecoinofficial/cocoapods-binary.git', :tag => 'v0.4.4.rev5'
  gem 'cocoapods-repo-update'
  gem 'cocoapods-keys'
  gem 'fastlane'
  gem 'pkg-config'
end
