source 'https://rubygems.org' do
  gem 'cocoapods', '~> 1.0', '>= 1.12.0'
  gem 'cocoapods-binary', :git => 'https://github.com/mobilecoinofficial/cocoapods-binary.git', :tag => 'v0.4.4.rev5'
  gem 'cocoapods-repo-update'
  gem 'cocoapods-keys'
  gem 'addressable', '2.8.5', :git => 'https://github.com/sporkmonger/addressable', :branch => 'main'
  gem 'cocoapods-deintegrate', '~> 1.0', '>= 1.0.4'
  gem 'fastlane'
  gem 'pkg-config'
end
