repos:
  - repo: local
    hooks:
      - id: autocorrect
        name: autocorrect
        entry: "tools/swiftlint.sh --fix --force-exclude"
        language: script
        files: \.swift$
  - repo: local
    hooks:
      - id: lint
        name: lint
        entry: "tools/swiftlint.sh --strict --quiet --force-exclude"
        language: script
        files: \.swift$
