# Rule list: https://github.com/realm/SwiftLint/blob/master/Rules.md
disabled_rules: # rule identifiers to exclude from running
  - nesting
  - opening_brace
  # disabled by default
  - conditional_returns_on_newline
  - file_types_order
  - missing_docs
  - no_grouping_extension
  - nslocalizedstring_require_bundle
  - extension_access_modifier
  - type_contents_order
  # consider enabling ones below
  - explicit_acl
  - identifier_name
  - empty_count
  - shorthand_operator
  - attributes
  - object_literal
  - discouraged_optional_collection
  - number_separator
  - vertical_whitespace_between_cases
  - multiline_arguments_brackets
  - vertical_whitespace_closing_braces
  - vertical_whitespace_opening_braces
  - trailing_closure
opt_in_rules: # some rules are only opt-in
  - anyobject_protocol
  - array_init
  - closure_body_length
  - closure_end_indentation
  - closure_spacing
  - collection_alignment
  - contains_over_first_not_nil
  - convenience_type
  - discouraged_object_literal
  - discouraged_optional_boolean
  - empty_count
  - empty_string
  - empty_xctest_method
  - explicit_init
  - explicit_self
  - fatal_error_message
  - file_header
  - file_name
  - first_where
  - force_unwrapping
  - function_default_parameter_at_end
  - identical_operands
  - implicit_return
  - implicitly_unwrapped_optional
  - joined_default_parameter
  - last_where
  - legacy_random
  - let_var_whitespace
  - literal_expression_end_indentation
  - lower_acl_than_parent
  - multiline_arguments
  - multiline_function_chains
  - multiline_parameters
  - multiline_parameters_brackets
  - no_extension_access_modifier
  - nslocalizedstring_key
  - operator_usage_whitespace
  - overridden_super_call
  - override_in_extension
  - pattern_matching_keywords
  - prefixed_toplevel_constant
  - private_action
  - private_outlet
  - prohibited_interface_builder
  - prohibited_super_call
  - reduce_into
  - redundant_nil_coalescing
  - redundant_type_annotation
  - single_test_class
  - sorted_first_last
  - sorted_imports
  - static_operator
  - strong_iboutlet
  - switch_case_on_newline
  - toggle_bool
  - unavailable_function
  - unneeded_parentheses_in_closure_argument
  - untyped_error_in_catch
  - unused_declaration
  - unused_import
  - vertical_parameter_alignment_on_call
  - xct_specific_matcher
  - yoda_condition
  # Find all the available rules by running:
  # swiftlint rules
included: # paths to include during linting. Ignored if `--path` is present unless `--force-exclude` is specified.
  - Sources
  - Tests
excluded: # paths to ignore during linting. Takes precedence over `included`.
# configurable rules can be customized from this configuration file
# binary rules can set their severity level
force_cast: warning # implicitly
force_try:
  severity: warning # explicitly
# rules that have both warning and error levels, can set just the warning level
# implicitly
line_length: 100
# they can set both implicitly with an array
type_body_length:
  - 300 # warning
  - 400 # error
# or they can set both explicitly
file_length:
  warning: 500
  error: 1200
# naming rules can set warnings/errors for min_length and max_length
# additionally they can set excluded names
type_name:
  min_length: 4 # only warning
  max_length: # warning and error
    warning: 40
    error: 50
  excluded: iPhone # excluded via string
identifier_name:
  excluded: ['i', 'n', 't', 'x']
reporter: "xcode" # reporter type (xcode, json, csv, checkstyle, junit, html, emoji, sonarqube, markdown)
trailing_comma:
    mandatory_comma: true
file_header:
  required_pattern: |
    \/\/
    \/\/  Copyright \(c\) \d{4}(?:-\d{4})? MobileCoin\. All rights reserved\.
    \/\/

# Temporarily turn this into a warning until the code is fixed
large_tuple:
  error: 6
