#!/bin/bash
set -e

function decrypt_secrets() {
  if ! [ -x "$(command -v age)" ]; then
  	brew install age;

    if ! [ -x "$(command -v age)" ]; then
  	  echo 'age is still not installed. install with `brew install age`' >&2
  	  exit 1
	  else 
      echo 'all dependencies installed, re-run this script' 
  	  exit 1
    fi
	fi

  security find-generic-password -a swift-repo-user -s swift-repo-private > /dev/null 2>&1

  script_path=$(readlink -f "${BASH_SOURCE}")
  script_dir=$(dirname "$script_path")
  project_dir=$(dirname "$script_dir")
  keys_encrypted="$project_dir/secrets/keys.encrypted"

  age -d -i <(security find-generic-password -w -s swift-repo-private) "$keys_encrypted"

}

decrypt_secrets
