#!/bin/bash
set -e

scriptdir="$( dirname -- "$BASH_SOURCE"; )";
source "$scriptdir/secrets_manager"

# execute check_dependencies silently, only report errors
# and exit if any dependencies are installed
check_dependencies -exit_on_install > /dev/null

decrypt_secrets
