#!/bin/bash

set -e

scriptdir="$( dirname -- "$BASH_SOURCE"; )";
source "$scriptdir/secrets_manager"

function encrypt_secrets_file() {
  if [ "$#" -ne 1 ]; then
    echo "Illegal number of parameters, specify a local unencrypted secrets file"
  else
    echo '----------------------------'
    echo 'Checking for valid secrets file'
    echo '----------------------------'

    if [ -s "$1" ]; then
      # The file is not-empty.
      echo '----------------------------'
      echo 'Secrets file found'
      echo '----------------------------'
    else
      # The file is empty.
      echo '----------------------------'
      echo 'Secrets file not found, check path'
      echo '----------------------------'
      exit 1;
    fi

    check_for_contributor_public_keys

    echo '----------------------------'
    echo 'Encrypting secrets'
    echo '----------------------------'

    keys_encrypted="$project_dir/secrets/keys.encrypted"
    age -e -R "$contributor_public_keys" -o "$keys_encrypted" "$1"

    echo '----------------------------'
    echo 'Complete! Checkin the changes and push to remote'
    echo '----------------------------'
}

check_dependencies

encrypt_secrets_file $1
