#!/bin/bash

set -e

scriptdir="$( dirname -- "$BASH_SOURCE"; )";
source "$scriptdir/secrets_manager"

function reencrypt_secrets() {
  echo '----------------------------'
  echo 'Checking for valid public keys file'
  echo '----------------------------'

  project_dir=$(project_directory)
  contributor_public_keys="$project_dir/secrets/contributor_public_keys"

  if [ -s "$contributor_public_keys" ]; then
    # The file is not-empty.
    echo '----------------------------'
    echo "$(wc -l < "$contributor_public_keys") Public keys found"
    echo '----------------------------'
  else
    # The file is empty.
    echo '----------------------------'
    echo 'Public keys file not found, or empty, run `generate_and_save_contributor_keys`'
    echo '----------------------------'
    exit 1;
  fi

  echo '----------------------------'
  echo 'Re-encrypting secrets'
  echo '----------------------------'

  keys_encrypted="$project_dir/secrets/keys.encrypted"
  age -e -R "$contributor_public_keys" -o "$keys_encrypted" ~/Projects/MobileCoin/scripts/keys.config

  echo '----------------------------'
  echo 'Complete! Checkin the changes and push to remote'
  echo '----------------------------'
}

check_dependencies

reencrypt_secrets
