#!/bin/bash

set -e

scriptdir="$( dirname -- "$BASH_SOURCE"; )";
source "$scriptdir/secrets_manager"

function reencrypt_secrets() {
  echo '----------------------------'
  echo 'Checking for valid public keys file'
  echo '----------------------------'

  project_dir=$(project_directory)
  contributor_public_keys="$project_dir/secrets/contributor_public_keys"

  check_for_contributor_public_keys

  echo '----------------------------'
  echo 'Re-encrypting secrets'
  echo '----------------------------'

  keys_encrypted="$project_dir/secrets/keys.encrypted"
  age -e -R "$contributor_public_keys" -o "$keys_encrypted" <(decrypt_secrets)

  echo '----------------------------'
  echo 'Complete! Checkin the changes and push to remote'
  echo '----------------------------'
}

check_dependencies

reencrypt_secrets
