#!/bin/bash

set -e

scriptdir="$( dirname -- "$BASH_SOURCE"; )";
source "$scriptdir/secrets_manager"

check_dependencies

echo "----------------------------"
echo "Re-initializing keys"
echo "----------------------------"

set_secrets "Example"
generate_and_rename_cocoapodkeys "Example"

set_secrets "ExampleHTTP"
generate_and_rename_cocoapodkeys "ExampleHTTP"
