#!/bin/bash

REPO_ROOT="$(git rev-parse --show-toplevel)"

source <(../scripts/decrypt_secrets)

jq --null-input \
  --arg DEV_NETWORK_AUTH_USERNAME "$DEV_NETWORK_AUTH_USERNAME" \
  --arg DEV_NETWORK_AUTH_PASSWORD "$DEV_NETWORK_AUTH_PASSWORD" \
  --arg TESTNET_TEST_ACCOUNT_MNEMONICS_COMMA_SEPERATED "$TESTNET_TEST_ACCOUNT_MNEMONICS_COMMA_SEPERATED" \
  --arg MOBILEDEV_TEST_ACCOUNT_MNEMONICS_COMMA_SEPERATED "$MOBILEDEV_TEST_ACCOUNT_MNEMONICS_COMMA_SEPERATED" \
  --arg DYNAMIC_TEST_ACCOUNT_SEED_ENTROPIES_COMMA_SEPARATED "$DYNAMIC_TEST_ACCOUNT_SEED_ENTROPIES_COMMA_SEPARATED" \
  --arg DYNAMIC_FOG_AUTHORITY_SPKI "$DYNAMIC_FOG_AUTHORITY_SPKI" \
  '{ "DEV_NETWORK_AUTH_USERNAME": $DEV_NETWORK_AUTH_USERNAME, "DEV_NETWORK_AUTH_PASSWORD":$DEV_NETWORK_AUTH_PASSWORD, "TESTNET_TEST_ACCOUNT_MNEMONICS_COMMA_SEPERATED":$TESTNET_TEST_ACCOUNT_MNEMONICS_COMMA_SEPERATED, "MOBILEDEV_TEST_ACCOUNT_MNEMONICS_COMMA_SEPERATED":$MOBILEDEV_TEST_ACCOUNT_MNEMONICS_COMMA_SEPERATED, "DYNAMIC_TEST_ACCOUNT_SEED_ENTROPIES_COMMA_SEPARATED":$DYNAMIC_TEST_ACCOUNT_SEED_ENTROPIES_COMMA_SEPARATED, "DYNAMIC_FOG_AUTHORITY_SPKI":$DYNAMIC_FOG_AUTHORITY_SPKI }' > $REPO_ROOT/Tests/Common/Secrets/secrets.json
