#!/bin/bash

set -eo pipefail

REPO_ROOT="$(git rev-parse --show-toplevel)"
source "$REPO_ROOT/scripts/secrets_manager"

# execute check_dependencies silently, only report errors
# and exit if any dependencies are installed
check_dependencies -exit_on_install > /dev/null

lookup() {
if [[ -z "$1" ]] ; then
  echo ""
else
  awk -v "id=$1" 'BEGIN { FS = "=" } $1 == id { print $2 ; exit }' <<< "$2"
fi
}

# One decryption for all six lookups. The assignment carries the age exit
# status, so a failure stops the script before jq truncates secrets.json.
SECRETS="$(decrypt_secrets | sed 's/export //')"

DEV_NETWORK_AUTH_USERNAME=$(echo $(lookup DEV_NETWORK_AUTH_USERNAME "$SECRETS")|xargs)
DEV_NETWORK_AUTH_PASSWORD=$(echo $(lookup DEV_NETWORK_AUTH_PASSWORD "$SECRETS")|xargs)
TESTNET_TEST_ACCOUNT_MNEMONICS_COMMA_SEPERATED=$(echo $(lookup TESTNET_TEST_ACCOUNT_MNEMONICS_COMMA_SEPERATED "$SECRETS")|xargs)
MOBILEDEV_TEST_ACCOUNT_MNEMONICS_COMMA_SEPERATED=$(echo $(lookup MOBILEDEV_TEST_ACCOUNT_MNEMONICS_COMMA_SEPERATED "$SECRETS")|xargs)
DYNAMIC_TEST_ACCOUNT_SEED_ENTROPIES_COMMA_SEPARATED=$(echo $(lookup DYNAMIC_TEST_ACCOUNT_SEED_ENTROPIES_COMMA_SEPARATED "$SECRETS")|xargs)
DYNAMIC_FOG_AUTHORITY_SPKI=$(echo $(lookup DYNAMIC_FOG_AUTHORITY_SPKI "$SECRETS") | sed 's/"//')

jq --null-input \
  --arg DEV_NETWORK_AUTH_USERNAME "$DEV_NETWORK_AUTH_USERNAME" \
  --arg DEV_NETWORK_AUTH_PASSWORD "$DEV_NETWORK_AUTH_PASSWORD" \
  --arg TESTNET_TEST_ACCOUNT_MNEMONICS_COMMA_SEPERATED "$TESTNET_TEST_ACCOUNT_MNEMONICS_COMMA_SEPERATED" \
  --arg MOBILEDEV_TEST_ACCOUNT_MNEMONICS_COMMA_SEPERATED "$MOBILEDEV_TEST_ACCOUNT_MNEMONICS_COMMA_SEPERATED" \
  --arg DYNAMIC_TEST_ACCOUNT_SEED_ENTROPIES_COMMA_SEPARATED "$DYNAMIC_TEST_ACCOUNT_SEED_ENTROPIES_COMMA_SEPARATED" \
  --arg DYNAMIC_FOG_AUTHORITY_SPKI "$DYNAMIC_FOG_AUTHORITY_SPKI" \
  '{ "DEV_NETWORK_AUTH_USERNAME": $DEV_NETWORK_AUTH_USERNAME, "DEV_NETWORK_AUTH_PASSWORD":$DEV_NETWORK_AUTH_PASSWORD, "TESTNET_TEST_ACCOUNT_MNEMONICS_COMMA_SEPERATED":$TESTNET_TEST_ACCOUNT_MNEMONICS_COMMA_SEPERATED, "MOBILEDEV_TEST_ACCOUNT_MNEMONICS_COMMA_SEPERATED":$MOBILEDEV_TEST_ACCOUNT_MNEMONICS_COMMA_SEPERATED, "DYNAMIC_TEST_ACCOUNT_SEED_ENTROPIES_COMMA_SEPARATED":$DYNAMIC_TEST_ACCOUNT_SEED_ENTROPIES_COMMA_SEPARATED, "DYNAMIC_FOG_AUTHORITY_SPKI":$DYNAMIC_FOG_AUTHORITY_SPKI }' > $REPO_ROOT/Tests/Common/Secrets/secrets.json
